name: build-and-test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: 1.20
        
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 1
        path: go/src/github.com/bom-squad/protobom

    - name: Test
      env:
        GOPATH: /home/runner/work/bom-squad/protobom
      run: |
        go get -d ./...
        go test -v ./...
